// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	object "ebanx/challenge/domain/object"

	mock "github.com/stretchr/testify/mock"
)

// BalanceUsecase is an autogenerated mock type for the BalanceUsecase type
type BalanceUsecase struct {
	mock.Mock
}

// Get provides a mock function with given fields: _a0
func (_m *BalanceUsecase) Get(_a0 string) (*object.Balance, error) {
	ret := _m.Called(_a0)

	var r0 *object.Balance
	if rf, ok := ret.Get(0).(func(string) *object.Balance); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*object.Balance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
