// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ResetUsecase is an autogenerated mock type for the ResetUsecase type
type ResetUsecase struct {
	mock.Mock
}

// Reset provides a mock function with given fields:
func (_m *ResetUsecase) Reset() {
	_m.Called()
}
